FROM apache/nifi:latest
USER root
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
RUN curl -L -o /opt/nifi/nifi-current/lib/mysql-connector-j-8.4.0.jar \
  https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.4.0/mysql-connector-j-8.4.0.jar \
  && chmod 644 /opt/nifi/nifi-current/lib/mysql-connector-j-8.4.0.jar
USER nifi
